import { Platform, StyleSheet } from 'react-native';

export const S = StyleSheet.create({
  // ── Loading ──────────────────────────────────────────────────────────────────
  loadingScreen: {
    flex: 1,
    backgroundColor: '#EEF2FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingLogoImage: {
    width: 120,
    height: 120,
  },
  loadingText: { marginTop: 16, color: '#374151', fontSize: 15 },
  loadingSpinnerWrap: {
    marginTop: 24,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingSpinnerRing: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 3,
    borderColor: 'rgba(91, 92, 246, 0.22)',
    borderTopColor: '#5B5CF6',
  },

  // ── Login ─────────────────────────────────────────────────────────────────────
  loginRoot: { flex: 1, backgroundColor: '#5B5CF6' },
  loginHero: {
    backgroundColor: '#5B5CF6',
    paddingHorizontal: 24,
    paddingBottom: 92,
    alignItems: 'center',
  },
  loginLogoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingVertical: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 12,
      },
      android: { elevation: 6 },
    }),
  },
  loginLogoImage: {
    width: 52,
    height: 52,
    marginRight: 12,
  },
  loginLogoTextWrap: { flex: 1 },
  loginLogoEyebrow: {
    color: '#6B7280',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  loginLogoTitle: { fontSize: 18, fontWeight: '800', color: '#381B63' },
  loginTagline: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 15,
    textAlign: 'left',
    alignSelf: 'flex-start',
    marginTop: 18,
    lineHeight: 22,
    maxWidth: 320,
  },
  loginSheet: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    marginTop: -44,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
  },
  loginSheetContent: { paddingHorizontal: 24, paddingTop: 28, paddingBottom: 24 },
  loginFieldLabel: {
    fontSize: 15,
    color: '#6E6482',
    fontWeight: '500',
    marginBottom: 12,
    lineHeight: 22,
  },
  loginMandatory: { color: '#F59E0B' },
  loginInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ECE8F8',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 6,
    backgroundColor: '#F4F1FC',
    minHeight: 54,
  },
  loginInputIcon: { fontSize: 16, marginRight: 8, color: '#6C63FF', width: 16 },
  loginPrefix: { fontSize: 15, color: '#59556C', fontWeight: '500', marginRight: 8 },
  loginTextInput: { flex: 1, fontSize: 15, color: '#1A1A2E', paddingVertical: 8 },
  loginHelperText: {
    fontSize: 12,
    color: '#9B95AB',
    lineHeight: 19,
    marginTop: 10,
    marginBottom: 18,
  },
  loginInlineRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  loginGetOtpBtn: {
    backgroundColor: '#6A67F6',
    borderRadius: 999,
    paddingHorizontal: 22,
    paddingVertical: 14,
    justifyContent: 'center',
  },
  loginGetOtpText: { color: '#FFFFFF', fontWeight: '700', fontSize: 14 },
  loginCodeBtn: {
    borderWidth: 1,
    borderColor: '#E3DDF5',
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 14,
    justifyContent: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#4338CA',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 6,
      },
      android: { elevation: 2 },
    }),
  },
  loginCodeBtnText: { color: '#5B5CF6', fontWeight: '700', fontSize: 13 },
  loginPrimaryBtn: {
    backgroundColor: '#625EF5',
    borderRadius: 999,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 22,
    marginBottom: 16,
    ...Platform.select({
      ios: {
        shadowColor: '#5B5CF6',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.35,
        shadowRadius: 10,
      },
      android: { elevation: 5 },
    }),
  },
  loginPrimaryBtnText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  loginTermsText: {
    fontSize: 11,
    color: '#948E9F',
    textAlign: 'center',
    lineHeight: 18,
    marginTop: 2,
  },
  loginTermsLink: { color: '#5B5CF6', fontWeight: '600' },

  // ── Shared screen header (purple) ─────────────────────────────────────────────
  screenHeader: {
    backgroundColor: '#5B5CF6',
    paddingHorizontal: 20,
    paddingBottom: 20,
    alignItems: 'center',
  },
  screenHeaderTitle: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  screenHeaderSub: { color: 'rgba(255,255,255,0.8)', fontSize: 13, marginTop: 4 },

  // ── Segmented control ─────────────────────────────────────────────────────────
  segWrap: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  seg: {
    flexDirection: 'row',
    backgroundColor: '#E5E7EB',
    borderRadius: 999,
    padding: 4,
  },
  segBtn: { flex: 1, paddingVertical: 9, alignItems: 'center', borderRadius: 999 },
  segBtnActive: { backgroundColor: '#5B5CF6' },
  segBtnText: { color: '#6B7280', fontWeight: '600', fontSize: 14 },
  segBtnTextActive: { color: '#FFFFFF' },

  // ── Loan cards ────────────────────────────────────────────────────────────────
  listContent: { padding: 16, gap: 12 },
  loanCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    gap: 8,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.07,
        shadowRadius: 8,
      },
      android: { elevation: 2 },
    }),
  },
  loanCardTop: { flexDirection: 'row', alignItems: 'flex-start' },
  loanIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#7C3AED',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  loanIcon: { fontSize: 20 },
  loanCardName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1A2E',
    flex: 1,
    marginRight: 8,
  },
  loanStatus: {
    color: '#F59E0B',
    fontSize: 12,
    fontWeight: '600',
    fontStyle: 'italic',
    flexShrink: 0,
    maxWidth: 130,
    textAlign: 'right',
  },
  loanCardId: { color: '#6B7280', fontSize: 12, marginTop: 2 },
  loanAmountLabel: { color: '#6B7280', fontSize: 12 },
  loanAmount: { fontSize: 22, fontWeight: '800', color: '#1A1A2E' },
  detailBtn: {
    backgroundColor: '#0EA5E9',
    borderRadius: 10,
    paddingHorizontal: 20,
    paddingVertical: 9,
  },
  detailBtnText: { color: '#FFFFFF', fontWeight: '700', fontSize: 14 },

  // ── Home redesign ─────────────────────────────────────────────────────────────
  homeRoot: { flex: 1, backgroundColor: '#F6F2FE' },
  homeContent: { paddingHorizontal: 14 },
  homeHeader: { marginBottom: 16 },
  homeWelcome: {
    fontSize: 16,
    color: '#A28FC1',
    marginBottom: 12,
  },
  homeHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  homeBrandWrap: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  homeBrandLogo: { width: 44, height: 44, marginRight: 12 },
  homeBrandName: {
    fontSize: 18,
    fontWeight: '800',
    color: '#3D2369',
  },
  homeBellBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E9E0F8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeBellIcon: { fontSize: 18, color: '#6F5AA7' },
  homeFeaturedCard: {
    overflow: 'hidden',
    borderRadius: 18,
    backgroundColor: '#241F3E',
    padding: 16,
    marginBottom: 28,
    ...Platform.select({
      ios: {
        shadowColor: '#241F3E',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.18,
        shadowRadius: 18,
      },
      android: { elevation: 5 },
    }),
  },
  homeFeaturedGlowRight: {
    position: 'absolute',
    right: -42,
    top: -26,
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: 'rgba(99,102,241,0.22)',
  },
  homeFeaturedGlowBottom: {
    position: 'absolute',
    left: 90,
    bottom: -40,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(124,58,237,0.18)',
  },
  homeFeaturedTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  homeCardBadge: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#FBBF24',
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeCardBadgeText: { color: '#241F3E', fontSize: 16, fontWeight: '700' },
  homeBrandPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  homeBrandPillDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#6A67F6',
    marginRight: 6,
  },
  homeBrandPillText: { color: 'rgba(255,255,255,0.82)', fontSize: 12 },
  homeFeaturedBottomRow: {
    marginTop: 34,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  homeFeaturedLabel: { fontSize: 14, color: 'rgba(255,255,255,0.7)', marginBottom: 6 },
  homeFeaturedAmount: {
    fontSize: 24,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.3,
  },
  homeRepayBtn: {
    borderRadius: 999,
    backgroundColor: '#6663F6',
    paddingHorizontal: 24,
    paddingVertical: 13,
  },
  homeRepayBtnText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
  homeSectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#4B2578',
    marginBottom: 14,
  },
  homeLoanCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 14,
    marginBottom: 16,
    ...Platform.select({
      ios: {
        shadowColor: '#3C155B',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.08,
        shadowRadius: 18,
      },
      android: { elevation: 3 },
    }),
  },
  homeLoanCardTop: { flexDirection: 'row', alignItems: 'flex-start' },
  homeLoanIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#9B46F6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  homeLoanIcon: { color: '#FFFFFF', fontSize: 18, fontWeight: '700' },
  homeLoanTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
  },
  homeLoanCardName: {
    flex: 1,
    fontSize: 16,
    fontWeight: '800',
    color: '#1F1729',
  },
  homeLoanStatus: {
    maxWidth: 130,
    fontSize: 12,
    fontWeight: '700',
    fontStyle: 'italic',
    color: '#F97316',
    textAlign: 'right',
  },
  homeLoanIdRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 14,
  },
  homeLoanIdLabel: { fontSize: 13, color: '#9B95AB' },
  homeLoanIdValue: { fontSize: 13, color: '#7B728E' },
  homeLoanBottomRow: {
    marginTop: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  homeLoanAmountLabel: { fontSize: 12, color: '#9B95AB', marginBottom: 4 },
  homeLoanAmount: { fontSize: 20, fontWeight: '800', color: '#1F1729' },
  homeDetailBtn: {
    backgroundColor: '#6663F6',
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  homeDetailBtnText: { color: '#FFFFFF', fontWeight: '700', fontSize: 13 },
  homePromoCard: {
    backgroundColor: '#5C4DF3',
    borderRadius: 18,
    overflow: 'hidden',
    padding: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  homePromoContent: { maxWidth: '68%' },
  homePromoTitle: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 10,
  },
  homePromoChip: {
    color: '#FFFFFF',
    fontSize: 12,
    backgroundColor: 'rgba(255,255,255,0.18)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    overflow: 'hidden',
  },
  homePromoCircle: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: 'rgba(255,255,255,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: -20,
    marginBottom: -20,
  },
  homePromoCurrency: { color: '#FFFFFF', fontSize: 34, fontWeight: '700' },

  // ── Order Detail ──────────────────────────────────────────────────────────────
  detailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(91,92,246,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backBtnText: { fontSize: 28, color: '#5B5CF6', marginTop: -2 },
  detailHeaderTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: '#1A1A2E',
  },
  detailContent: { padding: 16, gap: 14 },
  detailIconCircle: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#FCD34D',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  detailIconText: { fontSize: 32 },
  detailNotice: {
    color: '#374151',
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'center',
  },
  detailCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.07,
        shadowRadius: 8,
      },
      android: { elevation: 2 },
    }),
  },
  detailCardRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
  },
  detailCardDivider: { height: 1, backgroundColor: '#E5E7EB' },
  detailCardRowLabel: { color: '#6B7280', fontSize: 14 },
  detailCardRowValue: { color: '#1A1A2E', fontSize: 14, fontWeight: '600' },
  extensionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.07,
        shadowRadius: 8,
      },
      android: { elevation: 2 },
    }),
  },
  extensionTitle: { fontSize: 14, fontWeight: '600', color: '#1A1A2E' },
  extensionSub: { fontSize: 12, color: '#6B7280', marginTop: 2 },
  extensionBtn: {
    borderWidth: 1.5,
    borderColor: '#5B5CF6',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  extensionBtnText: { color: '#5B5CF6', fontWeight: '700', fontSize: 13 },
  repaymentBtn: {
    backgroundColor: '#5B5CF6',
    borderRadius: 16,
    paddingVertical: 17,
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#5B5CF6',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.35,
        shadowRadius: 10,
      },
      android: { elevation: 5 },
    }),
  },
  repaymentBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 1.2,
  },

  // ── Account ───────────────────────────────────────────────────────────────────
  accountHeader: {
    backgroundColor: '#5B5CF6',
    paddingHorizontal: 20,
    paddingBottom: 28,
    alignItems: 'center',
  },
  accountAvatarWrap: {
    width: 86,
    height: 86,
    borderRadius: 43,
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.26)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  accountAvatarIcon: {
    opacity: 0.96,
  },
  accountLabel: { color: '#FFFFFF', fontSize: 16, fontWeight: '600', letterSpacing: 0.5 },
  promoBanner: {
    backgroundColor: '#0EA5E9',
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
    borderRadius: 18,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#0EA5E9',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
      },
      android: { elevation: 4 },
    }),
  },
  promoBannerTitle: { color: '#FFFFFF', fontSize: 16, fontWeight: '700', lineHeight: 22 },
  promoBannerIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  promoBannerIcon: { fontSize: 28 },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1A2E',
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
  },
  accountList: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    borderRadius: 18,
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.07,
        shadowRadius: 8,
      },
      android: { elevation: 2 },
    }),
  },
  accountListDivider: { height: 1, backgroundColor: '#E5E7EB', marginLeft: 68 },
  accountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  accountRowIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  accountRowIconText: { fontSize: 17, color: '#FFFFFF', fontWeight: '700' },
  accountRowLabel: { flex: 1, fontSize: 15, color: '#1A1A2E', fontWeight: '500' },
  accountRowArrow: { fontSize: 22, color: '#6B7280' },
  accountRowArrowWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#ECEEFF',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ── Contact / Legal screens ───────────────────────────────────────────────────
  contactHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginBottom: 8,
  },
  contactBackBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  contactBackBtnText: { color: '#FFFFFF', fontSize: 28, marginTop: -3 },
  contactHeaderTitle: {
    flex: 1,
    textAlign: 'center',
    color: '#FFFFFF',
    fontSize: 19,
    fontWeight: '700',
  },
  contactContent: { padding: 16, gap: 12 },
  contactCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 10,
      },
      android: { elevation: 2 },
    }),
  },
  contactCardTitle: {
    fontSize: 13,
    color: '#6B7280',
    fontWeight: '600',
    marginBottom: 8,
  },
  contactCardValue: {
    fontSize: 16,
    color: '#111827',
    fontWeight: '700',
    marginBottom: 14,
  },
  contactActionBtn: {
    alignSelf: 'flex-start',
    backgroundColor: '#5B5CF6',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  contactActionBtnText: { color: '#FFFFFF', fontWeight: '700', fontSize: 13 },
  legalContent: { padding: 16, paddingBottom: 28 },
  legalIntro: {
    backgroundColor: '#EEF2FF',
    color: '#1E3A8A',
    borderRadius: 12,
    padding: 12,
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 14,
  },
  legalSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
      },
      android: { elevation: 1 },
    }),
  },
  legalSectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 6,
  },
  legalSectionBody: { fontSize: 13, lineHeight: 20, color: '#4B5563' },

  // ── Payment ───────────────────────────────────────────────────────────────────
  paymentRoot: { flex: 1, backgroundColor: '#E9E1F7' },
  paymentHeaderSafeArea: { backgroundColor: '#E7DDF8' },
  paymentHeader: {
    backgroundColor: '#E7DDF8',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 40,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: 'hidden',
  },
  paymentHeaderOrbRight: {
    position: 'absolute',
    right: -32,
    top: -24,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(60,21,91,0.06)',
  },
  paymentHeaderOrbLeft: {
    position: 'absolute',
    left: -28,
    bottom: -40,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(60,21,91,0.05)',
  },
  paymentHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  paymentBackBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.8)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(60,21,91,0.12)',
  },
  paymentBackBtnText: { fontSize: 28, color: '#3C155B', marginTop: -2 },
  paymentHeaderTitle: {
    fontSize: 19,
    fontWeight: '700',
    color: '#3C155B',
    letterSpacing: 0.1,
  },
  paymentScrollContent: {
    paddingHorizontal: 16,
    paddingTop: 10,
    marginTop: -18,
  },
  paymentCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 22,
    borderWidth: 1,
    borderColor: '#F1ECF8',
    ...Platform.select({
      ios: {
        shadowColor: '#3C155B',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.08,
        shadowRadius: 20,
      },
      android: { elevation: 5 },
    }),
  },
  paymentAmountIntro: {
    fontSize: 15,
    fontWeight: '500',
    color: '#52525B',
  },
  paymentAmountRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  paymentAmountHero: {
    fontSize: 34,
    fontWeight: '800',
    color: '#4338CA',
    letterSpacing: -0.4,
  },
  paymentDocBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF2FF',
  },
  paymentDocBadgeText: {
    fontSize: 18,
    color: '#4338CA',
    fontWeight: '700',
  },
  paymentTimer: {
    marginTop: 18,
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
    color: '#EF4444',
    letterSpacing: 0.8,
  },
  paymentQrSection: { marginTop: 28 },
  paymentQrTitle: {
    fontSize: 15,
    fontWeight: '500',
    color: '#18181B',
    textAlign: 'center',
  },
  paymentQrWrap: {
    alignSelf: 'center',
    marginTop: 16,
    width: 260,
    height: 260,
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E4E4E7',
    backgroundColor: '#F4F4F5',
    justifyContent: 'center',
  },
  paymentQrImage: {
    width: '100%',
    height: '100%',
  },
  paymentQrImageHidden: { opacity: 0.2 },
  paymentQrOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.38)',
  },
  paymentShowQrBtn: {
    borderRadius: 999,
    borderWidth: 2,
    borderColor: '#4338CA',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 22,
    paddingVertical: 11,
  },
  paymentShowQrBtnText: {
    color: '#4338CA',
    fontWeight: '700',
    fontSize: 14,
  },
  paymentMethodsSection: {
    marginTop: 32,
    paddingBottom: 6,
  },
  paymentMethodsHeading: {
    fontSize: 16,
    fontWeight: '700',
    color: '#18181B',
    textAlign: 'center',
    marginBottom: 16,
  },
  paymentMethodCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E4E4E7',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 12,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 6,
      },
      android: { elevation: 1 },
    }),
  },
  paymentMethodIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F4F4F5',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  paymentMethodIcon: { width: 32, height: 32 },
  paymentMethodLabel: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    color: '#18181B',
  },
  paymentMethodArrow: {
    fontSize: 24,
    color: '#A1A1AA',
    marginTop: -2,
  },
  paymentManualCard: {
    marginTop: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E4E4E7',
    backgroundColor: '#FFFFFF',
    padding: 16,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 6,
      },
      android: { elevation: 1 },
    }),
  },
  paymentManualHeading: {
    fontSize: 14,
    fontWeight: '700',
    color: '#18181B',
  },
  paymentManualStep: {
    fontSize: 12,
    fontWeight: '600',
    color: '#71717A',
    marginBottom: 8,
  },
  paymentManualCopyRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 8,
  },
  paymentManualUpiBox: {
    flex: 1,
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: '#F4F4F5',
    borderWidth: 1,
    borderColor: '#E4E4E7',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  paymentManualUpiText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#27272A',
  },
  paymentCopyBtn: {
    minWidth: 84,
    borderRadius: 10,
    backgroundColor: '#5C93E6',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  paymentCopyBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  paymentManualDivider: {
    height: 1,
    backgroundColor: '#F4F4F5',
    marginVertical: 18,
  },
  paymentManualPrompt: {
    fontSize: 14,
    fontWeight: '500',
    color: '#27272A',
    marginBottom: 10,
  },
  paymentRefLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#52525B',
    marginBottom: 6,
  },
  paymentRefInput: {
    borderWidth: 1,
    borderColor: '#E4E4E7',
    borderRadius: 10,
    backgroundColor: '#FAFAFA',
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 14,
    color: '#18181B',
  },
  paymentRefInputError: { borderColor: '#EF4444' },
  paymentRefError: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: '600',
    color: '#DC2626',
  },
  paymentManualHint: {
    marginTop: 10,
    fontSize: 12,
    lineHeight: 18,
    color: '#71717A',
  },
  paymentUtrHelpLinkWrap: {
    alignSelf: 'flex-end',
    marginTop: 10,
  },
  paymentUtrHelpLink: {
    fontSize: 13,
    fontWeight: '500',
    color: '#5C93E6',
  },
  paymentSubmitBtn: {
    marginTop: 18,
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: 'center',
    backgroundColor: '#4338CA',
    ...Platform.select({
      ios: {
        shadowColor: '#4338CA',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.25,
        shadowRadius: 10,
      },
      android: { elevation: 4 },
    }),
  },
  paymentSubmitBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  paymentModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    padding: 16,
  },
  paymentModalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    overflow: 'hidden',
  },
  paymentModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F4F4F5',
  },
  paymentModalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#18181B',
  },
  paymentModalCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  paymentModalCloseBtnText: {
    fontSize: 24,
    color: '#71717A',
    marginTop: -2,
  },
  paymentModalBody: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    fontSize: 14,
    lineHeight: 21,
    color: '#27272A',
  },
  paymentModalActions: {
    flexDirection: 'row',
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: '#F4F4F5',
    padding: 16,
  },
  paymentModalSecondaryBtn: {
    flex: 1,
    borderRadius: 14,
    backgroundColor: '#52525B',
    alignItems: 'center',
    paddingVertical: 14,
  },
  paymentModalSecondaryBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  paymentModalPrimaryBtn: {
    flex: 1,
    borderRadius: 14,
    backgroundColor: '#4338CA',
    alignItems: 'center',
    paddingVertical: 14,
  },
  paymentModalPrimaryBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  paymentImageModalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    overflow: 'hidden',
    maxHeight: '85%',
  },
  paymentImageModalTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    color: '#18181B',
  },
  paymentImageModalContent: { padding: 12 },
  paymentHelpImage: {
    width: '100%',
    height: 460,
  },

  // ── Tab bar ───────────────────────────────────────────────────────────────────
  tabBar: {
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    height: 64,
    paddingBottom: 8,
    paddingTop: 6,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
      },
      android: { elevation: 8 },
    }),
  },
  tabBarLabel: { fontSize: 11, fontWeight: '600' },
  tabIconActive: { fontSize: 22, color: '#5B5CF6' },
  tabIconInactive: { fontSize: 22, color: '#64748B', opacity: 0.45 },

  // ── Shared ────────────────────────────────────────────────────────────────────
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  emptyText: { textAlign: 'center', color: '#6B7280', marginTop: 48, fontSize: 15 },
  errorCard: {
    backgroundColor: '#FEF2F2',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  errorText: { color: '#DC2626', fontSize: 13, lineHeight: 18 },

  // ── Utility ───────────────────────────────────────────────────────────────────
  screenRoot: { flex: 1, backgroundColor: '#F4F4F9' },
  lavenderRoot: { flex: 1, backgroundColor: '#F0EFFE' },
  flex1: { flex: 1 },
  flex1ml12: { flex: 1, marginLeft: 12 },
  w40: { width: 40 },
  mt10: { marginTop: 10 },
  mt24: { marginTop: 24 },
  opacity06: { opacity: 0.6 },
  opacity07: { opacity: 0.7 },
  statusSettled: { color: '#10B981' },
});
